language: node_js

node_js:
- '0.11'
- '0.10'

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_success:
  - "find coverage -type f -name lcov.info -print0 | head -n 1 | xargs -0 cat | ./node_modules/coveralls/bin/coveralls.js"