language: node_js

node_js:
- '0.11'
- '0.10'

env:
  global:
    - secure: "irSrKRW2NaiUzP4efV+OmF2zMD2mpQfKuu/vHGch3h0dXWMbngA2WJonxxndJNZEJIU0dOrT061uA5F6nm3FAhGh1pAidvpQ/ptDC3m11pmsmQmuX/d+PxOAZQpabDdO3XIw3XKEhsTVAqze2HWBPnFvFTrEoQPbiiM7i0aSp/U="

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_success:
  # post coverage
  - "find coverage -type f -name lcov.info -print0 | head -n 1 | xargs -0 cat | ./node_modules/coveralls/bin/coveralls.js"
  # update demo
  - npm install -g couchapp
  - ./.deploy.sh $DESTINATION